### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by xsafedestix** [hpfxd/PandaSpigot#193]
Can you help? The server is shutting down itself.

[2024-04-19-3.log](https://github.com/hpfxd/PandaSpigot/files/15043330/2024-04-19-3.log)

**Comment by FirephoenixX02** [comment]
This seems more like a plugin issue. You have multiple plugins in your plugins folder with duplicate files, do not do that!, with some of them throwing multiple errors, some due to the wrong configuration? The server stopped responding after you executed the /is top command and in the stack trace we can see that the plugin executing the command was atleast part of the issue.

**Comment by uRyanxD** [comment]
Closing this issue, the question has already been answered above.
