### ISSUE TITLE
PandaSpigot terminal is broken/weird/incorrect

### ISSUE THREAD

**Issue by uRyanxD** [hpfxd/PandaSpigot#204]
Examples:
Earning an achievement
Marking a player as an operator

Paper:
https://prnt.sc/YUlf4yjYrhb6

Panda:
https://prnt.sc/NLVOj73PDpXt

Probable cause:
https://github.com/hpfxd/PandaSpigot/blob/master/patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch

**Comment by rodri-r-z** [comment]
This issue is chat-color related

I rebuilt PandaSpigot locally, and was able to fix it by changing

```java
public static String fromComponent(IChatBaseComponent component) {
    return fromComponent(component, EnumChatFormat.BLACK);
}
```

into

```java
public static String fromComponent(IChatBaseComponent component) {
    return fromComponent(component, EnumChatFormat.RESET);
}
```

In the class `CraftChatMessage.java` (`PandaSpigot-Server/src/main/java/org/bukkit/craftbukkit/util/CraftChatMessage.java`). The issue you mentioned [Console color is black by default](https://github.com/hpfxd/PandaSpigot/issues/183) was most likely marked as solved incorrectly.

Not submitting a pr over this tho.
