### ISSUE TITLE
Insight into a valid JAR file

### ISSUE THREAD

**Issue by HttpMarco** [hpfxd/PandaSpigot#234]
Hey guys,

At the moment, I’m developing a Minecraft cluster. Many supporters have suggested that we should offer version 1.8.9. However, I don’t want to mess around with the original Paper and handle bytecode with Java 17. Instead, I would like to use your fork as a reference for 1.8.9.

The only problem: I only receive a ZIP link, not a JAR link. Therefore, it’s not possible for me to support it without extra effort. Could you perhaps add something to your pipeline? This is what it looks like on our end right now, where PandaSpigot should also be added soon: https://github.com/HttpMarco/polocloud/blob/dev/release/versions.json

It would be great if you could manage that somehow.

Best regards,
HttpMarco

**Comment by jirmjahu** [comment]
@hpfxd

**Comment by hpfxd** [comment]
This is due to a limitation in how GitHub Actions handles artifact uploads; see actions/upload-artifact#426

Moving away from GH Actions and handling CI on my own infra is something I've considered for a long time and would allow for offering direct download links for JARs. Even without automated downloading by projects such as yours, this isn't the best user experience for end-users needing to unzip the downloaded file before use. I'll keep this issue open for now to track this being resolved.

As for right now, it seems like your options would be adding logic to unzip the downloaded file; or to setup some kind of service to proxy the JAR to be directly downloaded.

**Comment by hpfxd** [comment]
Implemented in 8393334acf551c2df5c2fdcc44b80e1974747e53

PandaSpigot now has a downloads API available at downloads.hpfxd.com. It is running a fork of bibliothek (Paper's download API), so should be compatible with your current process :) ([source code is available here for anyone interested](https://github.com/hpfxd/bibliothek))

The following URL will redirect to a download of the Paperclip server JAR for the latest build: `https://downloads.hpfxd.com/v2/projects/pandaspigot/versions/1.8.8/builds/latest/downloads/paperclip`
