### ISSUE TITLE
Incompatibility with ViaVersion/ViaRewind

### ISSUE THREAD

**Issue by ItsClairton** [hpfxd/PandaSpigot#65]
Hello, sorry for my English, but I came here to report that this fork has some kind of incompatibility with ViaVersion/ViaRewind.

We tested this fork in production, and many players playing on 1.7.10 reported being kicked from the server, here are screenshots of the errors, NOTE: for the server, it's as if they disconnected normally, so there are no errors.

![image](https://user-images.githubusercontent.com/28469592/206802934-0081b8d6-58f9-491a-afbc-e1d258717f46.png)
![image](https://user-images.githubusercontent.com/28469592/206802943-9f340611-9f05-4dc6-800d-efbf3465221c.png)
![image](https://user-images.githubusercontent.com/28469592/206804453-fc95dc1d-0d30-4897-b779-6e1e92def05c.png)

One thing we noticed is that ViaVersion cannot get the PPS of the players when we are using this fork.

**USING THE FORK:** 
![image](https://user-images.githubusercontent.com/28469592/206803068-9056fb5a-58db-4701-ba0a-cfd7178cfc6a.png)

**USING THE ORIGINAL SPIGOT:** 
![image](https://user-images.githubusercontent.com/28469592/206803173-3f7d8011-71a7-47fa-b8f8-7c278bf0afa7.png)

This problem only happens when we use the fork, we go back to the original spigot and we didn't have any report about it, the player is kicked randomly, there is no exact way to reproduce the error.

**Comment by mechoriet** [comment]
#52 could be related for some parts since its the same client

**Comment by mechoriet** [comment]
so far tested it by joining a server(not a local server so some network issues could also happen) with viaver and viarewind with lunarclient worked normally even after trying to force something by rejoining fast or trying to join while server was still  warming up

**Comment by ItsClairton** [comment]
I can't reproduce this on my localhost, or on a closed server only for the team, it seems that it's something involving a lot of packages at the same time, I'm trying to find a way to reproduce this to try to fix it.

This also happens in vanilla 1.7.10.

**Comment by andreasdc** [comment]
Try without plugins

**Comment by mechoriet** [comment]
coming back to that player are not displayed in `/viaversion pps` is cause of this : https://github.com/hpfxd/PandaSpigot/commit/b1017cd457646c1cf7da99c75d291cd2e7724dd0

its super late here now will check tomorrow(if time) If we can make something to show/track that ourselves or find a way to use viaversions one
or find a way to have both but they could interfere with each other

**Comment by ItsClairton** [comment]
If you take a dump using /viaver dump, you can see that ViaVersion is unable to grab Netty-related information.

**WITH FORK**: 

```json
    "injectionDump": {
        "injectedChannelInitializers": [],
        "wrappedLists": {},
        "currentLists": {}
    }```

USING THE ORIGINAL SPIGOT:
```json
    "injectionDump": {
        "injectedChannelInitializers": [
            {
                "futureClass": "io.netty.bootstrap.AbstractBootstrap$PendingRegistrationPromise",
                "channelClass": "io.netty.channel.epoll.EpollServerSocketChannel",
                "pipeline": [
                    {
                        "name": "ProtocolInjector$3#0",
                        "class": "com.comphenix.protocol.injector.netty.ProtocolInjector$3"
                    },
                    {
                        "name": "ServerBootstrap$ServerBootstrapAcceptor#0",
                        "class": "io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor",
                        "childClass": "com.viaversion.viaversion.bukkit.handlers.BukkitChannelInitializer",
                        "oldInit": "net.minecraft.server.v1_8_R3.ServerConnection$4"
                    },
                    {
                        "name": "DefaultChannelPipeline$TailContext#0",
                        "status": "INVALID"
                    }
                ]
            }
        ],
        "wrappedLists": {},
        "currentLists": {
            "g": "com.comphenix.protocol.injector.netty.BootstrapList"
        }
    }```

**Comment by uRyanxD** [comment]
I found the patch causing the problem: "Add Channel initialization listeners"

**Comment by uRyanxD** [comment]
After removing it, /viaver dump can detect the information as usual in PaperSpigot

**Comment by uRyanxD** [comment]
@ItsClairton Try using that version and see if the errors persist
https://www.mediafire.com/file/8qnymqccuadaghc/paperclip.jar/file

**Comment by hpfxd** [comment]
ViaVersion only tracks PPS if its built-in packet limiter is active, which is not the case when using PandaSpigot (it is disabled in favor of ours). See [`UserConnectionImpl.java:276`](https://github.com/ViaVersion/ViaVersion/blob/58442ec17718903323c0a867704d0df937ef1f26/common/src/main/java/com/viaversion/viaversion/connection/UserConnectionImpl.java#L276). The PPS counter is increased by `incrementReceived()`, which is not called here because `packetLimiterEnabled` is false.

The information in `/viaversion dump` not showing is caused by the channel initialization listeners patch being present. See the code responsible for the `injectionDump` section at [`LegacyViaInjector.java:175-236`](https://github.com/ViaVersion/ViaVersion/blob/58442ec17718903323c0a867704d0df937ef1f26/common/src/main/java/com/viaversion/viaversion/platform/LegacyViaInjector.java#L175-L236). When ViaVersion detects that it can utilize `ChannelInitializeListener`, the `injectedFutures` and `injectedLists` are no longer needed, so the information is not shown. `injectedFutures` is populated by [`injectChannelFuture(ChannelFuture)`](https://github.com/ViaVersion/ViaVersion/blob/58442ec17718903323c0a867704d0df937ef1f26/common/src/main/java/com/viaversion/viaversion/platform/LegacyViaInjector.java#L104), which is called by `inject()`. But as seen in [`BukkitViaInjector.java:46`](https://github.com/ViaVersion/ViaVersion/blob/58442ec17718903323c0a867704d0df937ef1f26/bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaInjector.java#L46) (subclass of LegacyViaInjector used on Bukkit), that `inject()` method is only called if `ChannelInitializeListener` is not present.

I'm going to say the behavior above is working as intended, as both also occur on Paper 1.19.3.

Whatever is causing the kicks is unrelated, and I'm unable to reproduce (tested using Vanilla and Forge 1.7.10 on PandaSpigot). Please feel free to re-open if you can find a way to reproduce or find more information.
