### ISSUE TITLE
Conflict with Multiverse Core (Works normally with Paper)

### ISSUE THREAD

**Issue by uRyanxD** [hpfxd/PandaSpigot#7]
Replacing server.jar from PaperSpigot to Panda causes NoSuchMethodException, full server logs:
https://paste.gg/p/anonymous/117dfa7c512f4696aea9ede5af713387

- Using latest 37 build

**Comment by hpfxd** [comment]
From the log you posted, it looks like Multiverse trying to call the old `getOnlinePlayers` method from around... Minecraft 1.6 I think? This doesn't work in PandaSpigot because we don't remap final jar with the deprecation mappings using SpecialSource (normal Spigot/Paper remaps the `_INVALID_getOnlinePlayers` method to `getOnlinePlayers` in org.bukkit.Bukkit, so there are 2 methods with the same name, just different return types)

I'm not sure if it's worth the time to fix this, as typically all it takes is recompiling a plugin with a newer version of the Bukkit API to resolve it. To resolve the issue with Multiverse you're having, it looks like its happening in their metrics system, so you could just ignore the error and it should still work fine. You can opt-out of their metrics in the `plugins/PluginMetrics/config.yml` file.

**Comment by uRyanxD** [comment]
Thanks

**Comment by uRyanxD** [comment]
I was able to fix this by upgrading to a version made for 1.10, it works perfectly in 1.8, if anyone has the same problem, use it.
https://dev.bukkit.org/projects/multiverse-core/files/2428161
